easy_admin:
    site_name: 'Codeurdulibre'

    user:
        name_property_path: 'email'
        display_avatar: false

    design:
        brand_color: '#aa3e98'
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
            - "@CKSourceCKFinder/Form/fields.html.twig"

        assets:
            js:
                - '/bundles/fosckeditor/ckeditor.js'
                - '/bundles/cksourceckfinder/ckfinder/ckfinder.js'
                - '/js/setup-ckfinder.js'

        menu:
          - { label: 'Blog'}
          - { entity: "Article", label: 'Mes Articles', icon: 'book'}
          - { entity: "ArticleCategory", label: 'Catégories', icon: 'bookmark'}
          - { entity: "ArticleTag", label: 'Tag', icon: 'tags'}
          - { label: 'Utilisateurs'}
          - { entity: "User", label: 'Utilisateurs', icon: 'users'}

    entities:
        Article:
            class: App\Entity\Article
            label: "Articles"
            form:
                title: "Ajouter un article"
                fields:
                  - { type: 'group', columns: 12, label: "Contenu" }
                  - { property: 'title', type: 'text'}
                  - { property: 'content', type: 'fos_ckeditor' , type_options:{ 'config': { 'toolbar': 'full' } }}
                  - { type: 'group', columns: 12, label: "Réglage" }
                  - { property: 'imagePath', type: 'CKSource\Bundle\CKFinderBundle\Form\Type\CKFinderFileChooserType'}
                  - { property: 'category', type: 'easyadmin_autocomplete'}
                  - { property: 'tags', type: 'easyadmin_autocomplete'}
                  - { property: 'publicationDate', type: 'date', label: "Date de publication"}
                  - { property: 'isPublished', label: "Publier"}
                  - { property: 'referArticles', type: 'easyadmin_autocomplete', label: "Articles en lien"}

        ArticleCategory:
            class: App\Entity\ArticleCategory
            label: "Categorie"

        ArticleTag:
            class: App\Entity\ArticleTag
            label: "Tag"

        Contact:
            class: App\Entity\Contact
            label: 'Contact via le site'
            disabled_actions: ['search', 'delete', 'edit', 'new']
            list:
                title: "Prise de contact"
                fields: ['id', 'username', 'email', 'subject', 'message']

        User:
            class: App\Entity\User
            controller: App\Controller\UserController
            label: "User"
            form:
                title: "Ajouter un utilisateur"
                fields:
                    - { property: 'email' }
                    - property: 'password'
                      type: 'repeated'
                      type_options:
                        type: Symfony\Component\Form\Extension\Core\Type\PasswordType
                        required: false
                        first_options: { label: 'Mot de passe' }
                        second_options: { label: 'Confirmer le mot de passe' }
                        invalid_message: fos_user.password.mismatch
                    - property: 'roles'
                      type: 'choice'
                      type_options:
                        mapped: true
                        expanded: true
                        multiple: true
                        choices: { 'Administrateur': 'ROLE_ADMIN' }