easy_admin:
  site_name: 'Codeurdulibre'

  user:
    name_property_path: 'email'
    display_avatar: false

  design:
    brand_color: '#aa3e98'
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
    assets:
      js:
        - '/bundles/fosckeditor/ckeditor.js'
        - '/bundles/cksourceckfinder/ckfinder/ckfinder.js'
        - '/js/setup-ckfinder.js'
    menu:
      - { label: 'Blog'}
      - { entity: "Article", label: 'Mes Articles', icon: 'users'}
      - { entity: "ArticleCategory", label: 'Catégories', icon: 'users'}

  entities:
    Article:
      class: Codeurdulibre\BlogBundle\src\Entity\Article
      label: "Articles"
    ArticleCategory:
      class: Codeurdulibre\BlogBundle\src\Entity\ArticleCategory
      label: "Categorie"
