<?php


namespace App\Entity;


class ArticleCategory extends \Odiseo\BlogBundle\Model\ArticleCategory
{
    public function __toString()
    {
        return parent::__toString(); // TODO: Change the autogenerated stub
    }
}